% [labels, start, stop] = Boris.CSV.load(filename)
% epochs = Boris.CSV.load(filename)
% Returns a list of event epochs generated by BORIS:

% 2021-02-26. Leonardo Molina.
% 2024-01-18. Last modified.
function varargout = load(filename)
    % Data is separated by commas.
    fid = fopen(filename, 'r');
    line = fgetl(fid);
    header = strsplit(line, ',');
    % Read all columns as text.
    format = repmat('%s', size(header));
    data = textscan(fid, format, 'Delimiter', ',');
    fclose(fid);
    % Parse target columns.
    labelsColumn = ismember(header, 'Behavior');
    startColumn = ismember(header, 'Start (s)');
    stopColumn = ismember(header, 'Stop (s)');
    labels = data{labelsColumn};
    start = str2double(data{startColumn});
    stop = str2double(data{stopColumn});

    % Number of outputs determines output format.
    if nargout == 1
        uLabels = unique(labels);
        nLabels = numel(uLabels);
        epochs = cell(1, 2 * nLabels);
        epochs(1:2:end) = uLabels;
        for u = 1:nLabels
            label = uLabels{u};
            k = ismember(labels, label);
            epochs{2 * u} = [start(k), stop(k)]';
        end
        varargout = {epochs};
    else
        varargout = {labels, start, stop};
    end
end