% events = loadCleverSysEvents(filename, sheet)
% Returns a map of events generated by CleverSys.
% 
% Example:
%   filename = 'data\sequential events - frame.xlsx';
%   sheet = 1;
%   events = loadCleverSysEvents(filename, sheet);
%   eventNames = events.keys;
%   name1 = eventNames{1};
%   name2 = eventNames{2};
%   mean1 = mean(events(name1).speed);
%   mean2 = mean(events(name2).speed);
%   plot([mean1, mean2], 'o');
%   xlim([0, 3]);
%   title(sprintf('Compare speeds between "%s" and "%s"', name1, name2));

% 2019-08-20. Leonardo Molina.
% 2020-10-06. Last modified.
function events = loadCleverSysEvents(filename, sheet)
    if nargin == 1
        sheet = 1;
    end
    if isnumeric(sheet)
        [~, sheetNames] = xlsfinfo(filename);
        sheetName = sheetNames{sheet};
    else
        sheetName = sheet;
    end
    state = warning('QUERY', 'MATLAB:datetime:AutoConvertStrings');
    warning('OFF', 'MATLAB:datetime:AutoConvertStrings');
    data = readcell(filename, 'Sheet', sheetName);
    warning(state.state, 'MATLAB:table:ModifiedAndSavedVarnames');
    
    [r, c] = find(cellfun(@(c) isequal(c, 'Event'), data));
    titles = data(r, :);
    eventList = data(r + 1:end, c);
    eventNames = unique(eventList);
    nEventNames = numel(eventNames);
    columns = [...
        find(cellfun(@(title) startsWith(title, 'From '), titles)), ...
        find(cellfun(@(title) startsWith(title, 'Length('), titles)), ...
        find(cellfun(@(title) startsWith(title, 'Dist('), titles)), ...
        find(cellfun(@(title) startsWith(title, 'V('), titles)) ...
    ];
    data = str2double(data(r + 1:end, columns));
    events = containers.Map();
    for e = 1:nEventNames
        eventName = eventNames{e};
        k = ismember(eventList, eventName);
        events(eventName) = struct('start', data(k, 1), 'duration', data(k, 2), 'distance', data(k, 3), 'speed', data(k, 4));
    end
end